import java.util.Random;
import java.util.Scanner;

public class GuessNumber {
    Scanner scanner = new Scanner(System.in);
    private Random rd = new Random();
    private int[] number = new int[4];
    private int[] goodNumber = new int[4];
    private int[] guessedNumber = new int[4];
    private int respGood;
    private int respRegular;
    private int counter = 0;

    public GuessNumber() {
        viewOfGame();
    }

    private void viewOfGame() {
        System.out.println("Bienvenido al juego GuessNumber");
    }

    private int giveAleatoryNum() {
        int aleatorTemp = rd.nextInt(10);
        return aleatorTemp;
    }

    /**
     * pass to array the number and identify as unique
     * number[] is a secret number generated by the pc
     */

    private void toArrayAleatoryNum() {
        int counter = 0;
        int aleatoryNum;
        boolean flag;
        while (counter < 4) {
            aleatoryNum = giveAleatoryNum();
            flag = false;
            for (int i = 0; i < number.length && !flag; i++) {
                if (aleatoryNum == number[i]) {
                    flag = true;
                }
            }
            if (flag) {
            } else {
                number[counter++] = aleatoryNum;
            }
        }
    }

    /**
     * This method compare the numbers aleatory created with the next number repeated
     */

    public void compareNumbers() {
        for (int i = 0; i < number.length; i++) {
            if (counter >= 2) {
                for (int j = 0; j < goodNumber.length; j++) {
                    if (goodNumber[j] == number[i]) {
                        number[j] = goodNumber[j];
                        System.out.println(number[j]);
                    }
                }
            } else {
                goodNumber[i] = number[i];
                System.out.println(goodNumber[i]);
            }
        }
    }

    /**
     * all the logic of the second game is here
     * @return te response good of the user, if resp=4 the game finished
     */

    public int logicBubleGame() {
        toArrayAleatoryNum();
        System.out.println("Tu numero es " + toString() + " ?");
        System.out.println("Ingrese los numeros Bien");
        respGood = scanner.nextInt();
        if (respGood == 1) {
            counter++;
            compareNumbers();
        }
        return respGood;
    }

    /**
     *
     * @return values ​​of the positions of the random arrNumbers
     */

    public String toString() {
        return "" + number[0] + number[1] + number[2] + number[3] + "";
    }
}
